#ifndef WIREDECK_CUDA_DENOISER_SHARED_H
#define WIREDECK_CUDA_DENOISER_SHARED_H

#define WIREDECK_CUDA_DENOISER_URI "https://wiredeck.dev/plugins/cuda-denoiser"
#define WIREDECK_CUDA_DENOISER_UI_URI "https://wiredeck.dev/plugins/cuda-denoiser#ui"

#define WIREDECK_CUDA_DENOISER_DEFAULT_MODELS_DIR "~/.config/wiredeck/models"
#define WIREDECK_CUDA_DENOISER_CONFIG_PATH "~/.config/wiredeck/plugins/cuda_denoiser.conf"

typedef enum WireDeckCudaDenoiserPortIndex {
  WD_PORT_ENABLED = 0,
  WD_PORT_THRESHOLD = 1,
  WD_PORT_BUFFER_MS = 2,
  WD_PORT_MIX = 3,
  WD_PORT_OUTPUT_GAIN_DB = 4,
  WD_PORT_GPU_INDEX = 5,
  WD_PORT_MODEL_INDEX = 6,
  WD_PORT_CUDA_AVAILABLE = 7,
  WD_PORT_GPU_COUNT = 8,
  WD_PORT_MODEL_COUNT = 9,
  WD_PORT_STATUS_CODE = 10,
  WD_PORT_INPUT_LEVEL = 11,
  WD_PORT_OUTPUT_LEVEL = 12,
  WD_PORT_MODEL_LOADED = 13,
  WD_PORT_RUNTIME_PHASE = 14,
  WD_PORT_INPUT_L = 15,
  WD_PORT_INPUT_R = 16,
  WD_PORT_OUTPUT_L = 17,
  WD_PORT_OUTPUT_R = 18,
} WireDeckCudaDenoiserPortIndex;

typedef enum WireDeckCudaDenoiserStatusCode {
  WD_STATUS_CUDA_READY = 0,
  WD_STATUS_CUDA_UNAVAILABLE = 1,
  WD_STATUS_NO_MODELS = 2,
  WD_STATUS_MODEL_INDEX_INVALID = 3,
  WD_STATUS_MODEL_FORMAT_UNSUPPORTED = 4,
  WD_STATUS_RUNTIME_NOT_IMPLEMENTED = 5,
  WD_STATUS_GPU_INDEX_INVALID = 6,
  WD_STATUS_MODEL_LOAD_FAILED = 7,
  WD_STATUS_CUDA_CONTEXT_FAILED = 8,
  WD_STATUS_WDGP_MODEL_READY = 9,
  WD_STATUS_KERNELS_MISSING = 10,
  WD_STATUS_KERNEL_LOAD_FAILED = 11,
  WD_STATUS_WEIGHTS_UPLOAD_FAILED = 12,
} WireDeckCudaDenoiserStatusCode;

typedef enum WireDeckCudaDenoiserRuntimePhase {
  WD_RUNTIME_IDLE = 0,
  WD_RUNTIME_LOADING = 1,
  WD_RUNTIME_RUNNING = 2,
  WD_RUNTIME_ERROR = 3,
  WD_RUNTIME_BYPASS = 4,
} WireDeckCudaDenoiserRuntimePhase;

#endif
