#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

OUTPUT_DIR=${OUTPUT_DIR:-"$SCRIPT_DIR/artifacts/gpu-supervised-run"}
INITIAL_CHECKPOINT=${INITIAL_CHECKPOINT:-"$SCRIPT_DIRartifacts/gpu-supervised-run/checkpoints/wiredeck_gpu_epoch_040.pt"}
EPOCHS=${EPOCHS:-12}
LR=${LR:-2e-5}
SPEECH_NOISE_REPEAT=${SPEECH_NOISE_REPEAT:-3}
CLEAN_PROBABILITY=${CLEAN_PROBABILITY:-0.18}
NOISE_ONLY_PROBABILITY=${NOISE_ONLY_PROBABILITY:-0.10}
SNR_MIN_DB=${SNR_MIN_DB:--8}
LOW_SPEECH_PROBABILITY=${LOW_SPEECH_PROBABILITY:-0.25}
VAD_LOSS_WEIGHT=${VAD_LOSS_WEIGHT:-0.30}
STATE_LOSS_WEIGHT=${STATE_LOSS_WEIGHT:-0.08}

export OUTPUT_DIR INITIAL_CHECKPOINT EPOCHS LR SPEECH_NOISE_REPEAT CLEAN_PROBABILITY
export NOISE_ONLY_PROBABILITY SNR_MIN_DB LOW_SPEECH_PROBABILITY VAD_LOSS_WEIGHT STATE_LOSS_WEIGHT

"$SCRIPT_DIR/train-supervised-common.sh"
