#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

OUTPUT_DIR=${OUTPUT_DIR:-"$SCRIPT_DIR/artifacts/gpu-supervised-run-v2"}
INITIAL_CHECKPOINT=
EPOCHS=${EPOCHS:-48}
LR=${LR:-7e-5}
SPEECH_NOISE_REPEAT=${SPEECH_NOISE_REPEAT:-5}
CLEAN_PROBABILITY=${CLEAN_PROBABILITY:-0.10}
NOISE_ONLY_PROBABILITY=${NOISE_ONLY_PROBABILITY:-0.12}
SNR_MIN_DB=${SNR_MIN_DB:--10}
LOW_SPEECH_PROBABILITY=${LOW_SPEECH_PROBABILITY:-0.18}
VAD_LOSS_WEIGHT=${VAD_LOSS_WEIGHT:-0.28}
STATE_LOSS_WEIGHT=${STATE_LOSS_WEIGHT:-0.06}
PREVIEW_AUDIO=${PREVIEW_AUDIO:-"$SCRIPT_DIR/artifacts/Audio_Sample_normalized/me_talking.wav"}
EXTRA_ARGS=${EXTRA_ARGS:---realtime-supervision}

export OUTPUT_DIR INITIAL_CHECKPOINT EPOCHS LR SPEECH_NOISE_REPEAT CLEAN_PROBABILITY
export NOISE_ONLY_PROBABILITY SNR_MIN_DB LOW_SPEECH_PROBABILITY VAD_LOSS_WEIGHT STATE_LOSS_WEIGHT
export PREVIEW_AUDIO EXTRA_ARGS

"$SCRIPT_DIR/train-supervised-common.sh"
